#    ______                        ______           _   _     _____
#    | ___ \                       |  _  \         | | | |   /  __ \
#   | |_/ /__ _ __ _ __ ___   __ _| | | |___  __ _| |_| |__ | /  \/ ___  _ __ ___
#   |  __/ _ \ '__| '_ ` _ \ / _` | | | / _ \/ _` | __| '_ \| |    / _ \| '__/ _ \
#   | | |  __/ |  | | | | | | (_| | |/ /  __/ (_| | |_| | | | \__/\ (_) | | |  __/
#   \_|  \___|_|  |_| |_| |_|\__,_|___/ \___|\__,_|\__|_| |_|\____/\___/|_|  \___|
#                                <- Developed by ->
#                                     @SebazCRC
#                              Version 1.0-PRE-RELEASE-2
#            |-----------|
#            | MIRATE EL |
#            | DISCORD   |
#            | ANTES DE  |
#            | USAR EL   |
#            | PLUGIN    |
#            |-----------|
#            (\__/) ||
#            (•ㅅ•) ||
#            / 　 づ
#           DISCORD: https://discord.gg/jWy9vJh
# Fecha que indica el inicio del servidor. (YYYY-MM-DD)
# Puedes cambiarla a tu gusto para adelantar los días o atrasarlos.
# Los días se cuentan como días que hayan pasado desde esa fecha
#
Fecha: ''
# Si deseas activar baneos al morir alguien
ban-enabled: true
# Si deseas que un jugador sea baneado al no entrar al servidor por X tiempo.
anti-afk-enabled: false
AntiAFK:
  # Días que necesita estar ausente un jugador para ser baneado.
  DaysForBan: 7
  # Jugadores inmunes
  # Escribe el nombre del jugador.
  Bypass:
    - SebazCRC
# Mensajes generales del servidor:
Server-Messages:
  DefaultDeathMessage: "&7%player% ha muerto y ahora descanza en paz."
  # ¡Agrega tus propios mensajes de muerte!
  # Escribe el nombre del jugador y su mensaje.
  # O puede usar en el juego /pdc mensaje <mensaje>
  CustomDeathMessages:
    SebazCRC: "No ha muerto, estaba probando"
# TOTEM CON PROBABILIDAD DE FALLAR
# La probabilidad necesitarás definirla por día, por ejemplo quieres un 1% en el día 25, colocas 25: 1
# Y así, si el plugin no detecta un día la probabilidad, el tótem no fallará
TotemFail:
  # ¿Deseas activar la probabilidad? | Sí: true | No: false
  Enable: true
  Medalla: '&7El jugador %player% ha usado su medalla de superviviente.'
  ChatMessage: '&7¡El tótem de &c%player% &7ha fallado!'
  ChatMessageTotems: '&7¡Los tótems de &c%player% &7han fallado!'
  NotEnoughTotems: '&7¡%player% no tenía suficientes tótems en el inventario!'
  PlayerUsedTotemMessage: '&7El jugador %player% ha consumido un tótem (Probabilidad: %totem_fail% %porcent% %number%)'
  PlayerUsedTotemsMessage: '&7El jugador %player% ha usado {ammount} tótems (Probabilidad: %totem_fail% %porcent% %number%)'
  FailProbs:
    30: 1
    31: 1
    32: 1
    33: 1
    34: 1
    35: 1
    36: 1
    37: 1
    38: 1
    39: 1
    40: 3
    41: 3
    42: 3
    43: 3
    44: 3
    45: 3
    46: 3
    47: 3
    48: 3
    49: 3
    50: 5
    51: 5
    52: 5
    53: 5
    54: 5
    55: 5
    56: 5
    57: 5
    58: 5
    59: 5
    60: 7
#
# ¡Define el mundo donde se ejecutará el Death train!
# También recomiendo escribir el nombre del mundo del End
Worlds:
  MainWorld: 'world'
  EndWorld: 'world_the_end'